language: sh
os: linux
arch: amd64
dist: bionic
sudo: required

services:
    - docker

before_deploy:
    - git config --local user.name "Travis CI IOx"
    - git config --local user.email "example@cisco.com"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG

script: 
    - chmod +x opc-plugin/travis-packaging.sh
    - sh opc-plugin/travis-packaging.sh

deploy:
    provider: releases
    file: /home/travis/build/soukudom/iot-app-server/opc-plugin/iox-opc-aarch64/package.tar
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    target_branch: build
    on:
        tags: true

after_deploy:
    - docker images

notifications:
    email: false

