language: python
arch: arm64 
dist: bionic
sudo: required

services:
  - docker

script:
  - docker build --tag iox-opc opc-plugin

after_script:
  - docker images

deploy:
  provider: script
  script: opc-plugin/travis-packaging.sh

after deploy:
  - ls -la

notifications:
  email: false