language: sh
os: linux
arch: amd64 
dist: bionic
sudo: required

services:
  - docker

deploy:
  provider: script
  script: chmod +x opc-plugin/travis-packaging.sh && sh opc-plugin/travis-packaging.sh
  on:
    branch: master

after-deploy:
  - docker images

notifications:
  email: false