language: sh
os: linux
arch: amd64
dist: bionic
sudo: required

services:
- docker

jobs:
  include:
  - stage: Creating Docker container/IOx package
  - script: chmod +x opc-plugin/travis-packaging.sh
  - script: sh opc-plugin/travis-packaging.sh
    deploy:
      provider: pages
      skip_cleanup: true
      local_dir: /home/travis/build/soukudom/iot-app-server/opc-plugin/iox-opc-aarch64/package.tar
      github_token: $GITHUB_TOKEN
      target_branch: build
      on:
        branch: master

after_deploy:
- docker images

