os: linux 
arch: arm64 
dist: bionic
language: python
sudo: required
services:
  - docker

script:
  - docker build --tag iox-opc opc-plugin
  - docker run -ti iox-opc

after_script:
  - docker images