language: sh
os: linux
arch: amd64
dist: bionic
sudo: required

services:
    - docker

script: 
    - chmod +x opc-plugin/travis-packaging.sh
    - sh opc-plugin/travis-packaging.sh

#before_deploy:
#    - git config --local user.name "Dominik Soukup"
#    - git config --local user.email "soukupdo@gmail.com"
#    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
#    - git tag $TRAVIS_TAG test2

deploy:
    provider: releases
    file: /home/travis/build/denfw/iot-app-server/opc-plugin/iox-opc-aarch64/package.tar
    skip_cleanup: true
    token: $GITHUB_TOKEN
    overwrite: true
    on:
        tags: true
        branch: master

notifications:
    email: false

