language: python
arch: arm64 
dist: xenial
sudo: required

# services:
#   - docker

# script:
#   - docker build --tag iox-opc opc-plugin

# after_script:
#   - docker images

deploy:
  provider: script
  script: chmod +x opc-plugin/travis-packaging.sh
  skip_cleanup: true
  on:
    branch: master

after deploy:
  - ls -la

notifications:
  email: false